### ISSUE TITLE
Latest version on Python 3.10 Windows

### ISSUE THREAD

**Issue by kot-shrodingera** [dhermes/bezier#295] opened 2022-07-15 00:37 UTC
Hi. I used your library with Python 3.9, everything is ok, but I want to move to 3.10
Regular `pip install bezier` does not install latest version
Am I right, that I need to install pure Python version? So I did (in powershell)
`$env:BEZIER_NO_EXTENSION='true'; pip install --upgrade bezier --no-binary=bezier`
But when I use something I get error
`
ImportError: ('No DLL directory found', [PackagePath('LICENSE'), PackagePath('MANIFEST.in'), PackagePath('README.rst'), PackagePath('setup.cfg'), PackagePath('setup.py'), PackagePath('src/python/bezier/__config__.py'), PackagePath('src/python/bezier/__init__.py'), PackagePath('src/python/bezier/_base.py'), PackagePath('src/python/bezier/_curve.pxd'), PackagePath('src/python/bezier/_curve_helpers.py'), PackagePath('src/python/bezier/_curve_intersection.pxd'), PackagePath('src/python/bezier/_geometric_intersection.py'), PackagePath('src/python/bezier/_helpers.pxd'), PackagePath('src/python/bezier/_helpers.py'), PackagePath('src/python/bezier/_intersection_helpers.py'), PackagePath('src/python/bezier/_legacy.py'), PackagePath('src/python/bezier/_plot_helpers.py'), PackagePath('src/python/bezier/_speedup.c'), PackagePath('src/python/bezier/_status.pxd'), PackagePath('src/python/bezier/_symbolic.py'), PackagePath('src/python/bezier/_triangle.pxd'), PackagePath('src/python/bezier/_triangle_helpers.py'), PackagePath('src/python/bezier/_triangle_intersection.pxd'), PackagePath('src/python/bezier/_triangle_intersection.py'), PackagePath('src/python/bezier/curve.py'), PackagePath('src/python/bezier/curved_polygon.py'), PackagePath('src/python/bezier/triangle.py'), PackagePath('src/python/bezier.egg-info/PKG-INFO'), PackagePath('src/python/bezier.egg-info/SOURCES.txt'), PackagePath('src/python/bezier.egg-info/dependency_links.txt'), PackagePath('src/python/bezier.egg-info/requires.txt'), PackagePath('src/python/bezier.egg-info/top_level.txt'), PackagePath('src/python/bezier.egg-info/zip-safe'), PackagePath('src/python/bezier/hazmat/__init__.py'), PackagePath('src/python/bezier/hazmat/algebraic_intersection.py'), PackagePath('src/python/bezier/hazmat/clipping.py'), PackagePath('src/python/bezier/hazmat/curve_helpers.py'), PackagePath('src/python/bezier/hazmat/geometric_intersection.py'), PackagePath('src/python/bezier/hazmat/helpers.py'), PackagePath('src/python/bezier/hazmat/intersection_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_helpers.py'), PackagePath('src/python/bezier/hazmat/triangle_intersection.py')])
`

**Comment by dhermes** [comment] 2022-07-15 01:28
@kot-shrodingera Thanks so much for taking the time to file an issue and for using my library!

I have been meaning to cut a release for awhile now but have just been busy, I'm so sorry. I am closing this as a duplicate of #273, feel free to follow along there for updates.

**Closed by dhermes** 2022-07-15 01:28 UTC
