### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by sorayadatio** [dhermes/bezier#187] opened 2020-01-20 08:40 UTC
Hi!

We have found a compatibility error, when using the last version of Bezier (0.11.0) with python 3.5.2 the following syntax error appears:

![imagen](https://user-images.githubusercontent.com/41906226/72711032-8f989300-3b68-11ea-8c31-944f0247cc15.png)

We hope it's helpful! :dancer:

**Comment by dhermes** [comment] 2020-01-20 16:44
@sorayadatio I really appreciate you taking the time to come by and report the issue. Based on the presence of `triangle.py` in your stack trace, it seems you're using the latest version `2020.1.14`. (See the [release notes][1] for the note about the `Surface` -> `Triangle` rename.)

The syntax-error is caused by `bezier`'s use of f-strings, which were introduced in Python 3.6. Though Python 3.5 doesn't reach it's [end of life][4] until 2020-09-13, the [`0.8.0` release][3] of `bezier` was the last to **explicitly** support 3.5:

![Screenshot from 2020-01-20 08-42-03](https://user-images.githubusercontent.com/520669/72743559-c5397e00-3b60-11ea-98b5-0d8d14ca7e6f.png)

As of the latest set of releases (i.e. [`2020.1.14`][2] and beyond), this project will explicitly support **at most** 3 Python versions at once. So the current versions are 3.6, 3.7 and 3.8. (Any support for earlier versions is incidental.)

----

I'm going to close this issue, but am happy to re-open to continue the discussion if you have questions, concerns or requests.

[1]: https://bezier.readthedocs.io/en/2020.1.14/releases/latest.html
[2]: https://pypi.org/project/bezier/2020.1.14/
[3]: https://pypi.org/project/bezier/0.8.0/
[4]: https://devguide.python.org/#status-of-python-branches

**Closed by dhermes** 2020-01-20 16:44 UTC
