### ISSUE TITLE
specialize function issue

### ISSUE THREAD

**Issue by markfink** [dhermes/bezier#207] opened 2020-02-26 08:21 UTC
I have 2D curves that I specialize (If you are curios I use them to create a CurvedPolygon for closing it I have a line from 1.0/0.0 -> 0.0/0.0).

Trying to specialize this line for the range (0.0, 0.4) I see the weird behaviour:

``` bash
>       np.testing.assert_array_equal(new_line._nodes, np.array([[0.4, 0.0], [0.0, 0.0]]))
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 2 / 4 (50%)
E       Max absolute difference: 0.6
E       Max relative difference: 1.5
E        x: array([[1. , 0.6],
E              [0. , 0. ]])
E        y: array([[0.4, 0. ],
E              [0. , 0. ]])
```

Here the testcase that reproduces the issue:

``` python
def test_specialize():
    nodes = np.array([
        [1.0, 0.0],
        [0.0, 0.0],
    ])
    line = bezier.Curve(nodes, degree=1)

    new_line = line.specialize(0.0, 0.4)
    print(f"new line: {new_line._nodes}")
    np.testing.assert_array_equal(new_line._nodes, np.array([[0.4, 0.0], [0.0, 0.0]]))
```

BTW: I tried closing the CurvedPolygon with the "inverse line".  And I get the following ValueError: ('Not sufficiently close', 'Consecutive sides do not have common endpoint', <Curve (degree=1, dimension=2)>, <Curve (degree=1, dimension=2)>)
So currently there is no obvious or at least no generic workaround.

**Comment by dhermes** [comment] 2020-02-26 15:48
It's really great to have users take the time to file an issue. Thank you for stopping by!

So the line you've got is of the form
```
B(s) = [1] (1 - s) + [0] s
       [0]           [0]
```

which means when you specialize to `[0, 0.4]` you'll get

```
C(s) = B(0) (1 - s) + B(0.4) s
```

I think the primary confusion is that your curve **starts** at `B(0) = [1.0, 0.0]^T` and so 40% of the way along the curve gives `B(0.4) = [0.6, 0.0]^T`.

I'm going to preemptively close out as "working as intended". Let me know if you'd like to continue discussion and I'm happy to re-open. (Not trying to slam the door on your question, just don't want to forget to close it.)

**Closed by dhermes** 2020-02-26 15:48 UTC

**Comment by dhermes** [comment] 2020-02-26 15:50
Regarding your comment about the `'Not sufficiently close` error with the `CurvedPolygon`, feel free to post the code for that here and I can try to help debug.

**Comment by markfink** [comment] 2020-02-26 15:59
wow, there is no way I would have guessed that start/ end are relative to the curve and not the axis. might be good to reflect that in the [documentation](https://bezier.readthedocs.io/en/latest/python/reference/bezier.curve.html#bezier.curve.Curve.specialize): 

```
Parameters
start (float) – The start point of the interval we are specializing to.
end (float) – The end point of the interval we are specializing to.
```
...does not really make that click.
Thank you for clearing that up.

**Comment by dhermes** [comment] 2020-02-27 03:49
Since these are parametric curves, they are by definition directed so you get to choose the start `B(0)` and end `B(1)` and all the control points in between. So the "natural" beginning and end that you get with the x-axis (or y-axis) doesn't apply (because the curve segment defines its own beginning and end).

**Comment by dhermes** [comment] 2020-02-27 03:49
I'll definitely toss around how I can expand on

> Specialize the curve to a given sub-interval.

to make it clearer.
