### ISSUE TITLE
Unable to run QuickStarts code

### ISSUE THREAD

**Issue by sjdqbyitr178crs813tgbr8gsdufygeuy53** [dhermes/bezier#83] opened 2017-11-16 11:48 UTC
Unable to run QuickStarts code at https://pypi.python.org/pypi/bezier
Shell is restarted after attempt to calculate curves intersection.
I have new clean Windows 7 64 bit python 3.6 installation with libraries: matplotlib, seaborn, bezier
IDLE console inputs and outputs:

```python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
>>> import bezier
>>> import numpy as np
>>> nodes1 = np.asfortranarray([
    [0.0, 0.0],
    [0.5, 1.0],
    [1.0, 0.0],
    ])
>>> 
>>> curve1 = bezier.Curve(nodes1, degree=2)
>>> nodes2 = np.asfortranarray([
    [0.0 ,  0.0],
    [0.25,  2.0],
    [0.5 , -2.0],
    [0.75,  2.0],
    [1.0 ,  0.0],
    ])
>>> 
>>> curve2 = bezier.Curve.from_nodes(nodes2)
>>> intersections = curve1.intersect(curve2)

=============================== RESTART: Shell ===============================
```

**Comment by dhermes** [comment] 2017-11-16 17:49
Thanks for reporting. That's strange indeed! Is there any other kind of error reporting?

It seems to me the most obvious issue would be the Fortran speedups, can you check a few things for me?

First verify the version:

```python
>>> import pkg_resources
>>> distribution = pkg_resources.get_distribution('bezier')
>>> distribution
bezier 0.5.0 (.../lib/python3.6/site-packages)
>>> distribution.version
'0.5.0'
```

Then, verify if speedups are installed:

```
>>> import bezier
>>> bezier._HAS_SPEEDUP
True
```

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment] 2017-11-17 04:33
No other reports, only shell restart.
Here is what you asked to do:
```Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import pkg_resources
>>> distribution = pkg_resources.get_distribution('bezier')
>>> distribution
bezier 0.5.0 (c:\python36\lib\site-packages)
>>> distribution.version
'0.5.0'
>>> import bezier
>>> bezier._HAS_SPEEDUP
True
>>> ```

**Comment by dhermes** [comment] 2017-11-17 04:38
Thanks. Can you run as just a Python script, rather than in IDLE?

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment] 2017-11-17 04:41
The code:

```
import pkg_resources
distribution = pkg_resources.get_distribution('bezier')
print('distribution =', distribution)
print('distribution.version =', distribution.version)
import bezier
print('bezier._HAS_SPEEDUP=', bezier._HAS_SPEEDUP)
```
And the output:
```
distribution = bezier 0.5.0
distribution.version = 0.5.0
bezier._HAS_SPEEDUP= True
```

**Comment by dhermes** [comment] 2017-11-17 04:43
Sorry, I meant the code that fails, i.e. running `.intersect()`

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment] 2017-11-17 04:48
For sure. See edited comment.

**Comment by dhermes** [comment] 2017-11-17 05:02
@sjdqbyitr178crs813tgbr8gsdufygeuy53 That's the IDLE shell. Can you run it with the regular Python executable? You can find it via:

```python
>>> import sys
>>> sys.executable
'.../.pyenv/versions/3.6.3/bin/python'
```

That path is (partially redacted) on my Linux install with `pyenv`. On Windows it will be different, I think it will either be `c:\python36\python` or `c:\python36\scripts\python`.

**Comment by sjdqbyitr178crs813tgbr8gsdufygeuy53** [comment] 2017-11-17 05:12
:))))))))

**Comment by dhermes** [comment] 2017-11-17 05:18
It's very interesting that there is no error reported. I unfortunately don't know enough about Windows to help further. I would recommend installing without the Fortran speedups. The easiest way to do this would be to install from source and set the `BEZIER_NO_EXTENSIONS` environment variable.

On Linix, this would look like:

```
$ export BEZIER_NO_EXTENSIONS=True
$ git clone https://github.com/dhermes/bezier/
$ cd bezier
$ pip install .
```

**Comment by dhermes** [comment] 2018-01-03 23:30
I am going to close this since conversation has stopped and there is little hope of reproducing the issue.

**Closed by dhermes** 2018-01-03 23:30 UTC
Labels: os: windows, type: investigating
